//Tasks
export const CREATE_TASK_INIT = 'CREATE_TASK_INIT';
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK_INIT = 'UPDATE_TASK_INIT';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_ONE_TASK_INIT = 'DELETE_ONE_TASK_INIT';
export const DELETE_ONE_TASK = 'DELETE_ONE_TASK';
export const DELETE_MULTIPLE_TASK_INIT = 'DELETE_MULTIPLE_TASK_INIT';
export const DELETE_MULTIPLE_TASK = 'DELETE_MULTIPLE_TASK';
export const GET_ALL_TASKS_INIT = 'GET_ALL_TASKS_INIT';
export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const GET_TASK_INIT = 'GET_TASK_INIT';
export const GET_TASK = 'GET_TASK';

//Lists
export const CREATE_LIST_INIT = 'CREATE_LIST_INIT';
export const CREATE_LIST = 'CREATE_LIST';
export const UPDATE_LIST_INIT = 'UPDATE_LIST_INIT';
export const UPDATE_LIST = 'UPDATE_LIST';
export const DELETE_ONE_LIST_INIT = 'DELETE_ONE_LIST_INIT';
export const DELETE_ONE_LIST = 'DELETE_ONE_LIST';
export const GET_ALL_LISTS_INIT = 'GET_ALL_LISTS_INIT';
export const GET_ALL_LISTS = 'GET_ALL_LISTS';
export const GET_LIST_INIT = 'GET_LIST_INIT';
export const GET_LIST = 'GET_LIST';

//Users
export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN = 'LOGIN';
export const SIGNUP_INIT = 'SIGNUP_INIT';
export const SIGNUP = 'SIGNUP';
export const AUTHENTICATE_TOKEN = 'AUTHENTICATE_TOKEN';
export const UPDATE_NAME_INIT = 'UPDATE_NAME_INIT';
export const UPDATE_NAME = 'UPDATE_NAME';
export const LOGOUT = 'LOGOUT';
export const CHECK_USER_AVAILABLE = 'CHECK_USER_AVAILABLE';